excerpt_separator: "<!--more-->"
highlighter: rouge
markdown: kramdown
url: http://mjclemente.github.io
title: Matthew J. Clemente
tagline: Always Trying to Be Better
description: Always trying to be better
gems: [jekyll-paginate]
paginate: 5