excerpt_separator: "<!--more-->"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: cfc
   ## line_numbers: true
title: Matthew J. Clemente
tagline: Always Trying to Be Better
description: Always trying to be better
plugins: [jekyll-paginate]
paginate: 5