excerpt_separator: "<!--more-->"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: cfc
   ## line_numbers: true
url: https://blog.mattclemente.com
title: Matthew J. Clemente
tagline: Always Trying to Be Better
description: Always trying to be better
author:
  name: Matthew J. Clemente
  email: mjclemente@gmail.com
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
paginate: 5
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"