excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mjclemente.github.io
title: Matthew J. Clemente
tagline: A log of everyday life
description: My awesome new site
gems: [jekyll-paginate]
paginate: 5